{
 "title": "Windows IIS Server",
 "description": "Windows IIS dashboard based on prometheus wmi_exporter",
 "tags": [
  "Windows",
  "IIS",
  "Prometheus",
  "wmi_exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(windows_iis_requests_total, alias)"
   },
   {
    "name": "instance",
    "label": "Website",
    "query": "label_values(windows_iis_current_connections{job=~\"$server.*\"}, site)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(windows_iis_worker_threads{job=~\"$server.*\"}, app)"
   }
  ]
 },
 "panels": [
  { "title": "IIS | Server URI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "URI Cache Flushes Total",
   "type": "graph",
   "description": "**URI Cache Flushes Total**",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_iis_server_uri_cache_flushes_total{job=~\"$server\"}",
     "legendFormat": "Flushes: {{ mode }}"
    },
    {
     "expr": "windows_iis_server_uri_cache_hits_total{job=~\"$server\"}",
     "legendFormat": "Hits: {{ mode }}"
    },
    {
     "expr": "windows_iis_server_uri_cache_items_flushed_total{job=~\"$server\"}",
     "legendFormat": "Items Flushed : {{ mode }}"
    },
    {
     "expr": "windows_iis_server_uri_cache_items_total{job=~\"$server\"}",
     "legendFormat": "Items : {{ mode }}"
    },
    {
     "expr": "windows_iis_server_uri_cache_queries_total{job=~\"$server\"}",
     "legendFormat": "Queries: {{ mode }}"
    }
   ]
  },
  {
   "title": "URI Cache Items",
   "type": "gauge",
   "description": "**URI Cache Items**",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "windows_iis_server_uri_cache_items{job=~\"$server\"}",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  { "title": "IIS | Server Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Metadata Cache Items",
   "type": "gauge",
   "description": "**Metadata Cache Items**",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "windows_iis_server_metadata_cache_items{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Metadata Cache Flushes",
   "type": "gauge",
   "description": "**Metadata Cache Flushes**",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "windows_iis_server_metadata_cache_flushes_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Metadata Cache Queries Total",
   "type": "singlestat",
   "description": "**Metadata Cache Queries Total**",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_metadata_cache_queries_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Metadata Cache Hits Total",
   "type": "singlestat",
   "description": "**Metadata Cache Hits Total**",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_metadata_cache_hits_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Metadata Cache Items Cached Total",
   "type": "singlestat",
   "description": "**Metadata Cache Items Cached Total**",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_metadata_cache_items_cached_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Metadata Cache Items Flushed Total",
   "type": "singlestat",
   "description": "**Metadata Cache Items Flushed Total**",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_metadata_cache_items_flushed_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Requests | GET/POST",
   "type": "graph",
   "description": "**Requests | GET/POST**\n\nNumber of HTTP requests (WebService.TotalRequests)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_requests_total{job=~\"$server\", site=~\"$instance\", method=\"GET\"}[$interval])",
     "legendFormat": "{{ method }} {{ site }}"
    },
    {
     "expr": "rate(windows_iis_requests_total{job=~\"$server\", site=~\"$instance\", method=\"POST\"}[$interval])",
     "legendFormat": "{{ method  }} {{ site }}"
    }
   ]
  },
  { "title": "IIS | Server File", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Cache Active Flushed Entries",
   "type": "gauge",
   "description": "**Cache Active Flushed Entries**\n\nNumber of file handles cached in user-mode that will be closed when all current transfers complete.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "windows_iis_server_cache_active_flushed_entries{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Memory Bytes",
   "type": "gauge",
   "description": "**File Cache Memory Bytes**",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_memory_bytes{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Items",
   "type": "gauge",
   "description": "**File Cache Items**",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_items{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Items Total",
   "type": "singlestat",
   "description": "**File Cache Items Total**",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_items_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Flushes Total",
   "type": "singlestat",
   "description": "**File Cache Flushes Total**",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_flushes_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Max Memory",
   "type": "singlestat",
   "description": "**File Cache Max Memory**",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 23 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_max_memory_bytes{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Queries Total",
   "type": "singlestat",
   "description": "**File Cache Queries Total**",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_queries_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "File Cache Hits Total",
   "type": "singlestat",
   "description": "**File Cache Hits Total**",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_file_cache_hits_total{job=~\"$server\"}"
    }
   ]
  },
  { "title": "IIS | Server Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Output Cache Flushes Total",
   "type": "singlestat",
   "description": "**Output Cache Flushes Total**",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_flushes_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Output Cache Active Flushed Items",
   "type": "singlestat",
   "description": "**Output Cache Active Flushed Items**",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_active_flushed_items{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Output Cache Items",
   "type": "singlestat",
   "description": "**Output Cache Items**",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_items{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Output Cache Items Flushed Total",
   "type": "singlestat",
   "description": "**Output Cache Items Flushed Total**",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_items_flushed_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Output Cache Memory Bytes",
   "type": "singlestat",
   "description": "**Output Cache Memory Bytes**",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 28 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_memory_bytes{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Output Cache Queries Total",
   "type": "singlestat",
   "description": "**Output Cache Queries Total**",
   "gridPos": { "h": 3, "w": 4, "x": 17, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_queries_total{job=~\"$server\"}"
    }
   ]
  },
  {
   "title": "Output Cache Hits Total",
   "type": "singlestat",
   "description": "**Output Cache Hits Total**",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "windows_iis_server_output_cache_hits_total{job=~\"$server\"}"
    }
   ]
  },
  { "title": "IIS | Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Current Connections",
   "type": "graph",
   "description": "**Current Connections**\n\nCurrent number of connections established with the Web service (WebService.CurrentConnections)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_current_connections{job=~\"$server\", site=~\"$instance\"}",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Send/Received Bytes",
   "type": "graph",
   "description": "**Send/Received Bytes**\n\nNumber of data bytes that have been sent by the Web service (WebService.TotalBytesSent)\n\nNumber of data bytes that have been received by the Web service (WebService.TotalBytesReceived)\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(windows_iis_sent_bytes_total{job=~\"$server\", site=~\"$instance\"}[$interval])",
     "legendFormat": "Sent Bytes : {{ site }}"
    },
    {
     "expr": "rate(windows_iis_received_bytes_total{job=~\"$server\", site=~\"$instance\"}[$interval])",
     "legendFormat": "Recieved Bytes : {{ site }}"
    }
   ]
  },
  {
   "title": "Rejected Async I/O Requests",
   "type": "graph",
   "description": "**Rejected Async I/O Requests**\n\nRequests rejected due to bandwidth throttling settings (WebService.TotalRejectedAsyncIORequests)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_rejected_async_io_requests_total{job=~\"$server\", site=~\"$instance\"}",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  {
   "title": "Blocked Async I/O Requests",
   "type": "graph",
   "description": "**Blocked Async I/O Requests**\n\nTotal requests temporarily blocked due to bandwidth throttling settings (WebService.TotalBlockedAsyncIORequests)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_blocked_async_io_requests_total{job=~\"$server\", site=~\"$instance\"}",
     "legendFormat": "{{ site }}"
    }
   ]
  },
  { "title": "IIS | Workers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Request Errors",
   "type": "graph",
   "description": "**Request Errors**",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_worker_request_errors_total{job=~\"$server\", app=~\"$application\"}",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "graph",
   "description": "**Request Errors**",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_worker_request_errors_total{job=~\"$server\", app=~\"$application\"}",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "Processes Created",
   "type": "graph",
   "description": "**Processes Created**\n\nThe number of worker processes created for the application pool since Windows Process Activation Service (WAS) started (TotalWorkerProcessesCreated)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_total_worker_processes_created{job=~\"$server\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Process Failures",
   "type": "graph",
   "description": "**Process Failures**\n\nThe number of times that worker processes have crashed since the application pool was started (TotalWorkerProcessFailures)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_total_worker_process_failures{job=~\"$server\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Ping Failures",
   "type": "graph",
   "description": "**Ping Failures**\n\nThe number of times that Windows Process Activation Service (WAS) did not receive a response to ping messages sent to a worker process (TotalWorkerProcessPingFailures)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_total_worker_process_ping_failures{job=~\"$server\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Startup Failures",
   "type": "graph",
   "description": "**Startup Failures**\n\nThe number of times that Windows Process Activation Service (WAS) failed to start a worker process (TotalWorkerProcessStartupFailures)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_total_worker_process_startup_failures{job=~\"$server\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Shutdown Failures",
   "type": "graph",
   "description": "**Shutdown Failures**\n\nThe number of times that Windows Process Activation Service (WAS) failed to shut down a worker process (TotalWorkerProcessShutdownFailures)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_total_worker_process_shutdown_failures{job=~\"$server\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  { "title": "IIS | Application Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Pool State Running",
   "type": "graph",
   "description": "**Pool State Running**\n\nThe current status of the application pool (1 - Uninitialized, 2 - Initialized, 3 - Running, 4 - Disabling, 5 - Disabled, 6 - Shutdown Pending, 7 - Delete Pending) (CurrentApplicationPoolState)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "windows_iis_current_application_pool_state{job=~\"$server\", state=\"Running\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Pool Start Time",
   "type": "graph",
   "description": "**Pool Start Time**\n\nThe unix timestamp for the application pool start time (CurrentApplicationPoolUptime)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "((windows_iis_current_application_pool_start_time{job=~\"$server\"}) * 1000)",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}